# Generated by Django 5.0.6 on 2024-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='feedback',
            field=models.TextField(default='Write Your Feedback here.', null=True),
        ),
    ]
