# Generated by Django 5.0.6 on 2024-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_policy_number',
            field=models.CharField(max_length=10),
        ),
    ]
