# Generated by Django 5.0.6 on 2024-05-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_insurance_policy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_Doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_Patient',
            field=models.BooleanField(default=True),
        ),
    ]
