# Generated by Django 5.0.6 on 2024-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_doctor_patient_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_Doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_Patient',
        ),
    ]
