# Generated by Django 5.0.6 on 2024-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_medical_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_license_number',
            field=models.CharField(max_length=10),
        ),
    ]
